In [5]:
 Reference : https://www.coryjmaklin.com/2018-12-26_Machine-Learning-Algorithms-Part-5--Random-Forest-Classification-In-Python-d96754b448c9/
# Problem statement
           #predict pure gold rate based on year and 22k gold rate - Regression

# load the dataset

import pandas as pd


dataset=pd.read_csv("gold_rate_history.csv")

print(dataset.info())
print(dataset.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4971 entries, 0 to 4970
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  4971 non-null   object
 1   Country               4971 non-null   object
 2   State                 4971 non-null   object
 3   Location              4971 non-null   object
 4   Pure Gold (24 k)      4971 non-null   float64
 5   Standard Gold (22 K)  4971 non-null   float64
dtypes: float64(2), object(4)
memory usage: 233.1+ KB
None
       Date Country      State Location  Pure Gold (24 k)  \
0  1/2/2006   India  Tamilnadu  Chennai             768.0
1  1/3/2006   India  Tamilnadu  Chennai             770.5
2  1/4/2006   India  Tamilnadu  Chennai             784.5
3  1/5/2006   India  Tamilnadu  Chennai             782.5
4  1/6/2006   India  Tamilnadu  Chennai             776.0

   Standard Gold (22 K)
0                 711.0
1                 713.0
2                 726.0
3                 725.0
4                 719.0

In [6]:
# Data Preprocessing
       # 1. Missing values 2. duplicate entries

# 3. data type formatting

dataset.dtypes

Date                     object
Country                  object
State                    object
Location                 object
Pure Gold (24 k)        float64
Standard Gold (22 K)    float64
dtype: object

In [8]:
# convert Date Col to datetime format

dataset['Date']=pd.to_datetime(dataset['Date'])



# Extract useful time features

dataset['year']=dataset['Date'].dt.year
dataset['month']=dataset['Date'].dt.month
dataset['day']=dataset['Date'].dt.day
dataset['dayofweek']=dataset['Date'].dt.dayofweek

In [9]:
dataset

,Date,Country,State,Location,Pure Gold (24 k),Standard Gold (22 K),year,month,day,dayofweek
0,2006-01-02,India,Tamilnadu,Chennai,768.0,711.0,2006,1,2,0
1,2006-01-03,India,Tamilnadu,Chennai,770.5,713.0,2006,1,3,1
2,2006-01-04,India,Tamilnadu,Chennai,784.5,726.0,2006,1,4,2
3,2006-01-05,India,Tamilnadu,Chennai,782.5,725.0,2006,1,5,3
4,2006-01-06,India,Tamilnadu,Chennai,776.0,719.0,2006,1,6,4
...,...,...,...,...,...,...,...,...,...,...
4966,2020-10-06,India,Tamilnadu,Chennai,5103.0,4860.0,2020,10,6,1
4967,2020-10-07,India,Tamilnadu,Chennai,5046.0,4806.0,2020,10,7,2
4968,2020-10-08,India,Tamilnadu,Chennai,5051.0,4810.0,2020,10,8,3
4969,2020-10-09,India,Tamilnadu,Chennai,5093.0,4850.0,2020,10,9,4
4970,2020-10-10,India,Tamilnadu,Chennai,5124.0,4881.0,2020,10,10,5

In [11]:
# Drop unnecssary columns

dataset=dataset.drop(['Date','Country','State','Location'],axis=1)

In [12]:
dataset

      Pure Gold (24 k)  Standard Gold (22 K)  year  month  day  dayofweek
0                768.0                 711.0  2006      1    2          0
1                770.5                 713.0  2006      1    3          1
2                784.5                 726.0  2006      1    4          2
3                782.5                 725.0  2006      1    5          3
4                776.0                 719.0  2006      1    6          4
...                ...                   ...   ...    ...  ...        ...
4966            5103.0                4860.0  2020     10    6          1
4967            5046.0                4806.0  2020     10    7          2
4968            5051.0                4810.0  2020     10    8          3
4969            5093.0                4850.0  2020     10    9          4
4970            5124.0                4881.0  2020     10   10          5

[4971 rows x 6 columns]