In [ ]:
Ml
workflow
     1. problem definition - define the objective
     2. Data collection - collection, identify the attributes ( features or input, target var, label, output)
     3. data preprocessing - Data cleaning( handle missing values , duplicates, data type formatting), feature scaling(standardization or normalization), encoding ( Gender - Male/Female)
     4. EDA ( Visualize feature distributes,analysis correleation between features, identify outliers)
     5. Feature Engineering  ( Patient ID, Hospital ID, patientname, BMI, age, Glue) - select important features)
     6. Data Spliting - Train(80%) Test (20%)  - validation (optional)
     7. Model Selection - ML algorithms - Supervised learning alg
     8. Train model (training set)
     9. Evalaute the model (accuracy, precision,recall, f1-score, confusion matrix, ROC-AUC curve)
     10.Hyperparameter tuning
     11. prediction (unknown data - test data)
     12. deployment ( REst API, web API, Web app)


ML - CPU , GPU , TPU   -CPU(why?) - it is not a complex data , simple dataset (<20,000 records)

ML
   - core Python
   - pandas, matplotlib, scipy, numpy, seaborn
   - scikit learn (python ML lib) - ML algorithms(supervised, unsupervised, reinforcement) - classes, functions, methods
   - pyspark (MLlib lib)

deployment
      web app - flask
      API - flask or FastAPI



Supervised LEarning alg
           - classification  (types - Binary (True/False)classification (only two classess in the output )
                                      Multi - class classification ( >=50k,<=50k ,50k)), Multi-label classification (multiple output)
                            - heart disease prediction based on the health metrics
           - regression    - output continuous value
                            - house price prediction, value  - gold price prediction
classification

In [ ]:
# problem statement
predict the customer will be going to purchase the product or not

In [2]:
# Data collection from different data sources

!pip install wget

Collecting wget
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: wget
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9655 sha256=91fd1b864ec25607acc6fe2cb50a50f831df702bf4491e42ea6e5ec3d6e87f5c
  Stored in directory: /root/.cache/pip/wheels/40/b3/0f/a40dbd1c6861731779f62cc4babcb234387e11d697df70ee97
Successfully built wget
Installing collected packages: wget
Successfully installed wget-3.2

In [3]:
import wget
wget.download('https://raw.githubusercontent.com/johnpaulantony/Machine-Learning/refs/heads/main/Logistic Regression/DigitalAd_dataset.csv')

'DigitalAd_dataset.csv'

In [6]:
# Data Exploration
# pandas - panel data system ( data analysis python lib)

#Pandas - two data sturutures - Series, DataFrame (1.0 - Panel)

import pandas as pd
dataset=pd.read_csv('DigitalAd_dataset.csv') # read_csv() - csv file format into dataframe (table format) object
type(dataset)
dataset

     Age  Salary  Status
0     18   82000       0
1     29   80000       0
2     47   25000       1
3     45   26000       1
4     46   28000       1
..   ...     ...     ...
395   35   65000       0
396   26   80000       0
397   26   52000       0
398   20   86000       0
399   32   18000       0

[400 rows x 3 columns]

In [ ]:
dataset.head()

   Age  Salary  Status
0   18   82000       0
1   29   80000       0
2   47   25000       1
3   45   26000       1
4   46   28000       1

In [ ]:
dataset.tail()

     Age  Salary  Status
395   35   65000       0
396   26   80000       0
397   26   52000       0
398   20   86000       0
399   32   18000       0

In [ ]:
dataset.shape

(400, 3)

In [ ]:
# Data preprocessing

# Data Cleaning

# missing values - NaN, None, NaT etc

dataset.isna().sum()

Age       0
Salary    0
Status    0
dtype: int64

In [ ]:
dataset.dtypes

Age       int64
Salary    int64
Status    int64
dtype: object

In [ ]:
pandas - int64, float64, object, bool, datetime64, timedelta64

In [10]:
# duplicated
dataset.duplicated().sum()

np.int64(33)

In [14]:
# Data Segregation - X or features or input  , Y (Target var, label, output)

X=dataset.loc[:, "Age":"Salary"].values
X

array([[    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],
       [    27,  17000],
       [    33,  51000],
       [    35, 108000],
       [    30,  15000],
       [    28,  84000],
       [    23,  20000],
       [    25,  79000],
       [    27,  54000],
       [    30, 135000],
       [    31,  89000],
       [    24,  32000],
       [    18,  44000],
       [    29,  83000],
       [    35,  23000],
       [    27,  58000],
       [    24,  55000],
       [    23,  48000],
       [    28,  79000],
       [    22,  18000],
       [    32, 117000],
       [    27,  20000],
       [    25,  87000],
       [    23,  66000],
       [    32, 120000],
       [    59,  83000],
       [    24,  58000],
       [    24,  19000],
       [    23,  82000],
       [    22,  63000],
       [    31,  68000],
       [    25,  80000],
       [    24,  27000],
       [    20,  23000],
       [    33, 113000],
       [    32,  18000],
       [    34, 112000],
       [    18,  52000],
       [    22,  27000],
       [    28,  87000],
       [    26,  17000],
       [    30,  80000],
       [    39,  42000],
       [    20,  49000],
       [    35,  88000],
       [    30,  62000],
       [    31, 118000],
       [    24,  55000],
       [    28,  85000],
       [    26,  81000],
       [    35,  50000],
       [    22,  81000],
       [    30, 116000],
       [    26,  15000],
       [    29,  28000],
       [    29,  83000],
       [    35,  44000],
       [    35,  25000],
       [    28, 123000],
       [    35,  73000],
       [    28,  37000],
       [    27,  88000],
       [    28,  59000],
       [    32,  86000],
       [    33, 149000],
       [    19,  21000],
       [    21,  72000],
       [    26,  35000],
       [    27,  89000],
       [    26,  86000],
       [    38,  80000],
       [    39,  71000],
       [    37,  71000],
       [    38,  61000],
       [    37,  55000],
       [    42,  80000],
       [    40,  57000],
       [    35,  75000],
       [    36,  52000],
       [    40,  59000],
       [    41,  59000],
       [    36,  75000],
       [    37,  72000],
       [    40,  75000],
       [    35,  53000],
       [    41,  51000],
       [    39,  61000],
       [    42,  65000],
       [    26,  32000],
       [    30,  17000],
       [    26,  84000],
       [    31,  58000],
       [    33,  31000],
       [    30,  87000],
       [    21,  68000],
       [    28,  55000],
       [    23,  63000],
       [    20,  82000],
       [    30, 107000],
       [    28,  59000],
       [    19,  25000],
       [    19,  85000],
       [    18,  68000],
       [    35,  59000],
       [    30,  89000],
       [    34,  25000],
       [    24,  89000],
       [    27,  96000],
       [    41,  30000],
       [    29,  61000],
       [    20,  74000],
       [    26,  15000],
       [    41,  45000],
       [    31,  76000],
       [    36,  50000],
       [    40,  47000],
       [    31,  15000],
       [    46,  59000],
       [    29,  75000],
       [    26,  30000],
       [    32, 135000],
       [    32, 100000],
       [    25,  90000],
       [    37,  33000],
       [    35,  38000],
       [    33,  69000],
       [    18,  86000],
       [    22,  55000],
       [    35,  71000],
       [    29, 148000],
       [    29,  47000],
       [    21,  88000],
       [    34, 115000],
       [    26, 118000],
       [    34,  43000],
       [    34,  72000],
       [    23,  28000],
       [    35,  47000],
       [    25,  22000],
       [    24,  23000],
       [    31,  34000],
       [    26,  16000],
       [    31,  71000],
       [    32, 117000],
       [    33,  43000],
       [    33,  60000],
       [    31,  66000],
       [    20,  82000],
       [    33,  41000],
       [    35,  72000],
       [    28,  32000],
       [    24,  84000],
       [    19,  26000],
       [    29,  43000],
       [    19,  70000],
       [    28,  89000],
       [    34,  43000],
       [    30,  79000],
       [    20,  36000],
       [    26,  80000],
       [    35,  22000],
       [    35,  39000],
       [    49,  74000],
       [    39, 134000],
       [    41,  71000],
       [    58, 101000],
       [    47,  47000],
       [    55, 130000],
       [    52, 114000],
       [    40, 142000],
       [    46,  22000],
       [    48,  96000],
       [    52, 150000],
       [    59,  42000],
       [    35,  58000],
       [    47,  43000],
       [    60, 108000],
       [    49,  65000],
       [    40,  78000],
       [    46,  96000],
       [    59, 143000],
       [    41,  80000],
       [    35,  91000],
       [    37, 144000],
       [    60, 102000],
       [    35,  60000],
       [    37,  53000],
       [    36, 126000],
       [    56, 133000],
       [    40,  72000],
       [    42,  80000],
       [    35, 147000],
       [    39,  42000],
       [    40, 107000],
       [    49,  86000],
       [    38, 112000],
       [    46,  79000],
       [    40,  57000],
       [    37,  80000],
       [    46,  82000],
       [    53, 143000],
       [    42, 149000],
       [    38,  59000],
       [    50,  88000],
       [    56, 104000],
       [    41,  72000],
       [    51, 146000],
       [    35,  50000],
       [    57, 122000],
       [    41,  52000],
       [    35,  97000],
       [    44,  39000],
       [    37,  52000],
       [    48, 134000],
       [    37, 146000],
       [    50,  44000],
       [    52,  90000],
       [    41,  72000],
       [    40,  57000],
       [    58,  95000],
       [    45, 131000],
       [    35,  77000],
       [    36, 144000],
       [    55, 125000],
       [    35,  72000],
       [    48,  90000],
       [    42, 108000],
       [    40,  75000],
       [    37,  74000],
       [    47, 144000],
       [    40,  61000],
       [    43, 133000],
       [    59,  76000],
       [    60,  42000],
       [    39, 106000],
       [    57,  26000],
       [    57,  74000],
       [    38,  71000],
       [    49,  88000],
       [    52,  38000],
       [    50,  36000],
       [    59,  88000],
       [    35,  61000],
       [    37,  70000],
       [    52,  21000],
       [    48, 141000],
       [    37,  93000],
       [    37,  62000],
       [    48, 138000],
       [    41,  79000],
       [    37,  78000],
       [    39, 134000],
       [    49,  89000],
       [    55,  39000],
       [    37,  77000],
       [    35,  57000],
       [    36,  63000],
       [    42,  73000],
       [    43, 112000],
       [    45,  79000],
       [    46, 117000],
       [    58,  38000],
       [    48,  74000],
       [    37, 137000],
       [    37,  79000],
       [    40,  60000],
       [    42,  54000],
       [    51, 134000],
       [    47, 113000],
       [    36, 125000],
       [    38,  50000],
       [    42,  70000],
       [    39,  96000],
       [    38,  50000],
       [    49, 141000],
       [    39,  79000],
       [    39,  75000],
       [    54, 104000],
       [    35,  55000],
       [    45,  32000],
       [    36,  60000],
       [    52, 138000],
       [    53,  82000],
       [    41,  52000],
       [    48,  30000],
       [    48, 131000],
       [    41,  60000],
       [    41,  72000],
       [    42,  75000],
       [    36, 118000],
       [    47, 107000],
       [    38,  51000],
       [    48, 119000],
       [    42,  65000],
       [    40,  65000],
       [    57,  60000],
       [    36,  54000],
       [    58, 144000],
       [    35,  79000],
       [    38,  55000],
       [    39, 122000],
       [    53, 104000],
       [    35,  75000],
       [    38,  65000],
       [    47,  51000],
       [    47, 105000],
       [    41,  63000],
       [    53,  72000],
       [    54, 108000],
       [    39,  77000],
       [    38,  61000],
       [    38, 113000],
       [    37,  75000],
       [    42,  90000],
       [    37,  57000],
       [    36,  99000],
       [    60,  34000],
       [    54,  70000],
       [    41,  72000],
       [    40,  71000],
       [    42,  54000],
       [    43, 129000],
       [    53,  34000],
       [    47,  50000],
       [    42,  79000],
       [    42, 104000],
       [    59,  29000],
       [    58,  47000],
       [    46,  88000],
       [    38,  71000],
       [    54,  26000],
       [    60,  46000],
       [    60,  83000],
       [    39,  73000],
       [    59, 130000],
       [    37,  80000],
       [    46,  32000],
       [    46,  74000],
       [    42,  53000],
       [    41,  87000],
       [    58,  23000],
       [    42,  64000],
       [    48,  33000],
       [    44, 139000],
       [    49,  28000],
       [    57,  33000],
       [    56,  60000],
       [    49,  39000],
       [    39,  71000],
       [    47,  34000],
       [    48,  35000],
       [    48,  33000],
       [    47,  23000],
       [    45,  45000],
       [    60,  42000],
       [    39,  59000],
       [    46,  41000],
       [    51,  23000],
       [    50,  20000],
       [    36,  33000],
       [    49,  36000],
       [    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000]])

In [ ]:
X=dataset.iloc[:,0:2].values
X

In [15]:
Y=dataset.loc[:,'Status'].values
Y

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0])

In [11]:
# Data Splitting - train and test data

# sklearn module - all ML alg written in this lib


!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.6.0)

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X,Y, test_size=0.2,random_state=0)

In [34]:
len(X_train)

320

In [35]:
len(Y_train)

320

In [36]:
len(X_test) == len(Y_test)

True

In [37]:
# feature scaling - model will give prioroty for all features during training

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [38]:
X_train

array([[ 0.02212156,  1.24324249],
       [-0.9344866 ,  0.46784687],
       [-0.64750415, -0.09878838],
       [-0.16920007,  0.10997197],
       [ 0.11778238,  0.22926361],
       [ 1.74401625,  0.97483631],
       [-1.69977312,  0.31873233],
       [ 0.11778238, -0.00931966],
       [-0.26486088, -0.18825711],
       [ 0.11778238,  1.51164866],
       [ 0.11778238, -0.36719456],
       [-0.07353925,  0.08014907],
       [-1.22146904,  0.25908652],
       [ 0.97872972, -0.90400691],
       [ 1.93533788,  0.88536759],
       [-0.55184333,  0.85554468],
       [-1.69977312,  0.08014907],
       [-1.79543394,  0.13979488],
       [ 1.36137299, -0.99347563],
       [ 0.30910401,  0.46784687],
       [ 0.97872972,  0.5573156 ],
       [-1.50845149, -1.32152762],
       [ 0.30910401,  0.02050325],
       [-0.3605217 , -0.84436109],
       [ 0.50042564,  1.21341958],
       [-0.16920007,  0.82572177],
       [-0.26486088, -0.81453818],
       [ 0.40476483,  0.22926361],
       [-0.26486088, -0.00931966],
       [ 0.02212156, -0.63560073],
       [ 0.11778238, -0.00931966],
       [-0.45618252,  2.31686718],
       [ 0.40476483, -0.03914257],
       [-0.26486088, -1.32152762],
       [ 1.93533788, -1.44081925],
       [-0.26486088,  2.25722137],
       [ 0.11778238,  1.03448213],
       [-0.55184333,  1.45200285],
       [ 0.97872972,  1.86952356],
       [ 0.30910401,  0.02050325],
       [-1.12580823, -1.08294436],
       [-0.07353925,  0.25908652],
       [ 0.30910401, -0.57595492],
       [-0.26486088, -0.63560073],
       [ 0.88306891, -1.44081925],
       [ 0.78740809, -0.36719456],
       [-0.45618252, -1.29170471],
       [ 0.2134432 ,  0.10997197],
       [ 0.40476483,  0.97483631],
       [-0.55184333,  1.36253412],
       [-0.45618252, -0.06896548],
       [-0.55184333,  2.34669009],
       [-0.74316496,  0.25908652],
       [ 1.17005136, -0.81453818],
       [ 0.2134432 ,  1.06430504],
       [ 0.2134432 , -0.42684037],
       [ 0.30910401, -0.33737165],
       [ 0.2134432 ,  2.10810683],
       [ 1.4570338 ,  0.97483631],
       [-1.03014741,  1.95899229],
       [-1.31712986, -1.44081925],
       [-0.26486088, -0.96365272],
       [-0.9344866 ,  0.37837815],
       [-0.74316496, -1.6197567 ],
       [ 1.07439054,  0.49766978],
       [-0.16920007, -0.57595492],
       [ 0.11778238,  0.05032616],
       [ 0.69174728,  1.78005484],
       [-0.26486088,  0.76607596],
       [-0.64750415, -0.39701747],
       [ 0.88306891,  1.00465922],
       [-0.9344866 , -0.48648619],
       [-0.07353925,  0.22926361],
       [ 0.40476483, -0.18825711],
       [ 0.40476483,  0.25908652],
       [-1.12580823, -1.67940252],
       [-0.07353925,  0.1994407 ],
       [-1.79543394,  0.40820106],
       [ 2.0309987 , -0.874184  ],
       [ 1.07439054,  2.07828392],
       [-0.16920007, -0.24790292],
       [ 0.30910401, -1.2320589 ],
       [-1.03014741, -0.5163091 ],
       [ 0.69174728, -0.78471527],
       [-0.26486088, -0.72506946],
       [-0.74316496,  1.89934647],
       [ 1.26571217,  2.22739846],
       [-0.07353925, -0.00931966],
       [-0.9344866 , -1.02329854],
       [-0.3605217 ,  1.21341958],
       [-0.64750415, -0.00931966],
       [ 0.40476483,  0.05032616],
       [ 0.88306891, -0.84436109],
       [-1.03014741, -0.39701747],
       [ 0.30910401,  0.02050325],
       [ 0.97872972,  0.08014907],
       [ 0.2134432 ,  0.10997197],
       [-1.03014741, -1.53028798],
       [ 1.83967707, -0.33737165],
       [-1.12580823,  0.25908652],
       [ 0.78740809,  0.31873233],
       [-0.9344866 ,  0.40820106],
       [ 0.30910401, -0.78471527],
       [ 0.78740809, -0.90400691],
       [ 0.02212156,  1.21341958],
       [-0.26486088, -0.33737165],
       [-0.74316496, -1.67940252],
       [-0.3605217 , -0.84436109],
       [-0.07353925,  0.25908652],
       [-0.07353925,  0.64678432],
       [-1.31712986, -0.39701747],
       [ 0.02212156, -0.18825711],
       [ 1.93533788, -0.72506946],
       [-0.45618252, -0.60577782],
       [ 0.88306891, -1.38117344],
       [ 0.11778238, -0.874184  ],
       [-1.60411231,  0.49766978],
       [-0.16920007,  1.63094029],
       [ 0.97872972, -1.14259017],
       [ 0.78740809,  0.22926361],
       [-0.64750415,  0.13979488],
       [ 0.59608646, -0.96365272],
       [ 1.07439054,  0.43802396],
       [ 0.30910401,  0.22926361],
       [ 1.64835544, -0.96365272],
       [ 1.4570338 ,  0.31873233],
       [-0.07353925,  2.22739846],
       [-0.64750415,  0.52749269],
       [ 0.78740809,  0.73625305],
       [-1.03014741,  0.37837815],
       [ 0.11778238, -0.874184  ],
       [-1.12580823,  0.02050325],
       [ 1.4570338 ,  0.02050325],
       [-1.50845149, -1.5899338 ],
       [ 1.36137299,  0.5573156 ],
       [-0.74316496,  0.52749269],
       [-1.03014741,  0.52749269],
       [ 0.11778238, -0.30754874],
       [-1.12580823, -1.64957961],
       [-1.03014741, -0.42684037],
       [ 1.17005136, -1.53028798],
       [ 1.55269462, -0.03914257],
       [-1.03014741, -0.39701747],
       [-1.60411231, -1.64957961],
       [ 0.69174728,  0.22926361],
       [-0.83882578, -1.29170471],
       [-0.26486088,  0.02050325],
       [-1.22146904, -1.14259017],
       [-0.64750415,  1.39235703],
       [ 0.88306891, -1.2320589 ],
       [ 0.97872972, -1.14259017],
       [ 1.74401625,  1.83970065],
       [ 1.07439054, -1.05312145],
       [-1.12580823, -0.84436109],
       [ 1.17005136,  0.49766978],
       [-0.3605217 ,  0.02050325],
       [ 0.2134432 , -0.36719456],
       [-1.41279068, -1.29170471],
       [-0.9344866 ,  1.54147157],
       [ 0.30910401, -0.00931966],
       [-1.12580823, -0.57595492],
       [-0.74316496,  0.46784687],
       [ 0.88306891,  2.16775264],
       [ 0.11778238,  1.86952356],
       [-0.07353925,  2.16775264],
       [ 0.97872972, -1.08294436],
       [ 0.30910401, -0.60577782],
       [-0.26486088, -0.99347563],
       [-0.3605217 ,  1.3028883 ],
       [-1.50845149, -0.48648619],
       [-0.64750415,  0.08014907],
       [ 1.36137299, -1.50046507],
       [-0.26486088, -0.63560073],
       [-0.26486088, -0.54613201],
       [-0.26486088,  0.10997197],
       [ 2.0309987 ,  2.13792973],
       [ 0.88306891,  1.06430504],
       [-0.16920007, -0.63560073],
       [-0.07353925, -0.57595492],
       [ 0.2134432 , -0.18825711],
       [ 1.64835544,  1.60111739],
       [ 0.30910401, -0.57595492],
       [-0.9344866 , -0.81453818],
       [ 0.40476483,  2.31686718],
       [ 1.36137299,  1.98881519],
       [ 0.69174728, -1.35135053],
       [ 0.11778238,  1.86952356],
       [-1.79543394, -1.38117344],
       [-0.74316496,  1.33271121],
       [-1.12580823,  0.25908652],
       [ 0.11778238,  0.10997197],
       [ 2.12665952, -0.874184  ],
       [ 0.50042564,  1.72040902],
       [-0.74316496,  0.22926361],
       [ 2.12665952, -0.75489236],
       [-0.83882578,  0.34855524],
       [ 2.12665952, -0.874184  ],
       [ 0.88306891, -1.53028798],
       [ 0.02212156, -0.63560073],
       [-1.03014741,  0.49766978],
       [ 2.0309987 ,  0.49766978],
       [-1.31712986, -1.17241308],
       [ 1.26571217, -1.44081925],
       [-1.69977312, -1.44081925],
       [-1.31712986, -0.48648619],
       [ 0.97872972,  2.07828392],
       [ 2.0309987 ,  0.34855524],
       [ 2.12665952,  0.9151905 ],
       [ 0.97872972,  1.42217994],
       [ 0.02212156, -0.60577782],
       [ 0.30910401, -0.24790292],
       [-0.74316496,  1.06430504],
       [ 0.2134432 , -0.42684037],
       [-1.89109476, -0.57595492],
       [ 1.55269462,  0.97483631],
       [-0.3605217 , -1.38117344],
       [ 1.07439054,  0.08014907],
       [-0.74316496, -0.66542364],
       [-0.9344866 ,  0.22926361],
       [-1.89109476,  0.31873233],
       [ 2.12665952,  1.09412795],
       [-0.07353925, -0.42684037],
       [ 0.02212156, -0.30754874],
       [-0.26486088, -1.53028798],
       [-0.83882578, -0.84436109],
       [ 0.50042564,  1.83970065],
       [-1.12580823,  0.43802396],
       [ 1.07439054, -1.29170471],
       [ 0.02212156,  0.25908652],
       [ 2.0309987 , -1.26188181],
       [-0.45618252, -0.84436109],
       [-0.26486088,  0.49766978],
       [-0.16920007, -0.33737165],
       [-1.41279068, -0.1584342 ],
       [-0.26486088,  0.58713851],
       [-0.07353925,  0.16961779],
       [ 0.02212156, -0.36719456],
       [-0.07353925, -1.14259017],
       [-0.83882578,  0.10997197],
       [-0.9344866 ,  0.52749269],
       [-1.31712986,  0.52749269],
       [ 2.12665952,  0.34855524],
       [-1.69977312,  0.43802396],
       [ 0.02212156, -0.00931966],
       [ 0.02212156, -0.48648619],
       [ 0.2134432 ,  0.1994407 ],
       [-0.26486088,  0.05032616],
       [-1.41279068, -0.24790292],
       [ 0.40476483, -0.5163091 ],
       [ 0.40476483, -0.21808002],
       [-1.60411231,  0.02050325],
       [-0.26486088, -1.38117344],
       [-0.26486088, -0.30754874],
       [-1.60411231, -0.09878838],
       [ 0.40476483, -0.5163091 ],
       [-1.31712986, -1.32152762],
       [-0.16920007, -0.5163091 ],
       [ 2.0309987 ,  0.13979488],
       [ 1.55269462, -1.35135053],
       [-1.41279068, -0.69524655],
       [ 0.30910401, -0.36719456],
       [ 0.59608646,  2.0186381 ],
       [ 0.97872972,  1.98881519],
       [ 0.78740809,  0.49766978],
       [-0.83882578,  0.34855524],
       [-1.41279068,  0.31873233],
       [ 1.4570338 , -1.11276726],
       [-0.26486088, -0.36719456],
       [ 0.2134432 , -0.33737165],
       [-0.26486088,  1.09412795],
       [-1.69977312, -1.05312145],
       [-1.22146904, -1.47064216],
       [-1.89109476,  0.43802396],
       [ 1.93533788,  0.70643014],
       [ 1.07439054, -0.18825711],
       [-1.41279068, -1.53028798],
       [-1.22146904,  0.22926361],
       [-1.89109476, -0.09878838],
       [-0.26486088, -1.47064216],
       [ 1.07439054, -0.96365272],
       [-0.07353925,  1.95899229],
       [ 0.78740809,  0.08014907],
       [-1.22146904,  0.5573156 ],
       [ 0.78740809,  1.36253412],
       [ 1.83967707, -1.14259017],
       [-1.79543394, -1.35135053],
       [-0.07353925, -0.48648619],
       [ 0.40476483,  0.5573156 ],
       [ 0.02212156, -0.30754874],
       [ 1.36137299,  2.34669009],
       [ 0.2134432 , -0.42684037],
       [-1.12580823,  0.37837815],
       [ 1.17005136, -1.05312145],
       [-1.31712986, -0.48648619],
       [ 1.55269462,  1.09412795],
       [-1.03014741, -1.20223599],
       [-0.64750415, -1.11276726],
       [-0.07353925,  0.10997197],
       [-0.16920007, -1.14259017],
       [-0.26486088,  0.02050325],
       [-1.79543394, -1.56011089],
       [-0.26486088, -1.44081925],
       [ 1.36137299,  1.2730654 ],
       [-0.16920007,  1.39235703],
       [-0.55184333,  0.43802396],
       [-0.74316496, -0.27772583],
       [-0.9344866 , -0.36719456],
       [ 1.26571217,  1.86952356],
       [ 0.30910401,  0.02050325],
       [ 1.07439054,  0.52749269],
       [-0.07353925, -0.54613201],
       [ 0.69174728, -1.47064216],
       [ 2.0309987 ,  1.75023193],
       [ 0.78740809, -1.47064216],
       [ 0.40476483,  1.09412795],
       [-0.26486088,  0.22926361],
       [ 1.64835544,  1.75023193],
       [-0.45618252, -1.20223599],
       [-1.22146904,  0.46784687],
       [-1.69977312,  0.31873233]])

In [40]:
# select alg
from sklearn.linear_model import LogisticRegression
sales_model=LogisticRegression(random_state=0)
sales_model.fit(X_train,Y_train)

LogisticRegression(random_state=0)

In [41]:
from sklearn.metrics import accuracy_score
y_pred=sales_model.predict(X_test)
result_score=accuracy_score(Y_test,y_pred)
result_score

0.7875

In [43]:
age=int(input("enter the age"))
salary=int(input("enter the salary"))
new_user=sc.transform([[age,salary]])
new_user

result=sales_model.predict(new_user)
if result==1:
    print("customer will purchase")
else:
    print("customer will not purchase")

enter the age32
enter the salary117000
customer will not purchase